import Head from "next/head";
import Link from "next/link";
import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import Paragraph from "@/components/Paragraph";
import { Button } from "@/components/mui";

export default function Custom500() {
  return (
    <>
      <Head>
        <title>Page not found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2" sx={{color: "#021691", p: 2, fontWeight: 500, textAlign: "center"}}>
          Server Error
        </Heading>
        <Paragraph sx={{color: "#021691", p: 2, fontWeight: 500, textAlign: "center"}}>
          The server is unavailable at the moment. Please try again later.
        </Paragraph>
        <Button href="/" component={Link} variant="contained" sx={{display: "flex", justifyContent: "center", alignItems: "center", width: "auto", p: 2}}>
          Back to home page
        </Button>
      </Layout>
    </>
  );
}